version: '2'

services:

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme

  elkarbackup:
    image: elkarbackup/elkarbackup:dev
    ports:
      - 80:80
      - 443:443
    links:
      - db
    depends_on:
      - db
    environment:
      EB_DB_PASSWORD: changeme
      EB_PATH: /usr/local/elkarbackup
      EB_VERSION: https://github.com/xezpeleta/elkarbackup.git
    volumes:
      - /srv/eb/src:/usr/local/elkarbackup
