version: '3'

services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    #volumes:
    #  - /srv/mysql:/var/lib/mysql

  elkarbackup:
    image: elkarbackup/elkarbackup:latest
    #build: .
    ports:
      - 80:80
      - 443:443
    links:
      - db
    depends_on:
      - db
    #volumes:
      #- /srv/elkarbackup/data:/var/spool/elkarbackup
      #- /srv/elkarbackup:/usr/share/elkarbackup
      #- /srv/elkarbackup/logs:/var/log/elkarbackup
    environment:
      EB_DB_HOST: db
      #EB_DB_USER: root
      EB_DB_PASSWORD: example
      #EB_DB_USERPASSWORD: elkarbackup
